core_entrance:
  backend:
    controller:
      Test Text: { route: 'backend_test', category: 'Tests'}
      Test Tabelle: { route: 'backend_table', category: 'Tests'}
      Test Form: { route: 'backend_form', category: 'Tests'}
      Seitenbaum: { route: 'page', category: 'Seiten'}
      News: { route: 'news', category: 'News'}
      News Categories: { route: 'newscategory', category: 'News'}
      Games: { route: 'games', category: 'Games' }
      Events: { route: 'events', category: 'Events' }
      Applications: { route: 'applications', category: 'Applications' }