# SecurityBundle
SecurityBundleFrontend:
    resource: "@CoreSecurityBundle/Resources/config/frontend.yml"

SecurityBundleBackend:
    resource: "@CoreSecurityBundle/Resources/config/backend.yml"
    prefix: /admin





# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
