CoreSecurityBundle:
    resource: "@CoreSecurityBundle/Resources/config/routing.xml"
    prefix:   /

AdminLogin:
     pattern:   /admin/login
     defaults:  { _controller: CoreSecurityBundle:Security:login }


SystemPageBundle:
    resource: "@SystemPageBundle/Resources/config/routing.xml"
    prefix:   /

CoreEntranceBundle:
    resource: "@CoreEntranceBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
