CoreInstallingBundle:
    resource: "@CoreInstallingBundle/Resources/config/routing.yml"
    prefix:   /

# CoreBundle
EntranceBundleFrontend:
    resource: "@CoreEntranceBundle/Resources/config/frontend.yml"

EntranceBundleBackend:
    resource: "@CoreEntranceBundle/Resources/config/backend.yml"
    prefix: /admin

# SecurityBundle
SecurityBundleFrontend:
    resource: "@CoreSecurityBundle/Resources/config/frontend.yml"

SecurityBundleBackend:
    resource: "@CoreSecurityBundle/Resources/config/backend.yml"
    prefix: /admin

login:
  pattern:  /login
  defaults: { _controller: CoreSecurityBundle:Security:login }

login_check:
  pattern:  /login_check



# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
