backend:
   pattern:  /
   defaults: { _controller: CoreEntranceBundle:Backend:index }

backend_category:
   pattern: /category/{category}
   defaults: { _controller: CoreEntranceBundle:BackendEntrance:selectCategory }

backend_test:
   pattern:  /test
   defaults: { _controller: CoreEntranceBundle:Backend:test }

backend_table:
  pattern:  /table
  defaults: { _controller: CoreEntranceBundle:Backend:table }

backend_form:
  pattern:  /form
  defaults: { _controller: CoreEntranceBundle:Backend:form }
