backend_welcome:
   pattern:  /welcome
   defaults: { _controller: CoreEntranceBundle:BackendEntrance:index }

backend_test:
   pattern:  /test
   defaults: { _controller: CoreEntranceBundle:Test:index }

backend_table:
  pattern:  /table
  defaults: { _controller: CoreEntranceBundle:Test:table }
