news:
    pattern:  /news
    defaults: { _controller: SystemNewsBundle:NewsBackend:index }

news_new:
    pattern: /news/new
    defaults: { _controller: SystemNewsBundle:NewsBackend:new }
    
news_show:
    pattern: /news/{id}/show
    defaults: { _controller: SystemNewsBundle:NewsBackend:show }
    requirements:
          id:  \d+

news_create:
    pattern: /news/create
    defaults: { _controller: SystemNewsBundle:NewsBackend:create }

news_edit:
    pattern: /news/{id}/edit
    defaults: { _controller: SystemNewsBundle:NewsBackend:edit }
    requirements:
          id:  \d+
    
news_update:
    pattern: /news/{id}/update
    defaults: { _controller: SystemNewsBundle:NewsBackend:update }
    requirements:
          id:  \d+
    
news_delete:
    pattern: /news/{id}/delete
    defaults: { _controller: SystemNewsBundle:NewsBackend:delete }
    requirements:
          id:  \d+

newscategory:
    pattern:  /news_category
    defaults: { _controller: SystemNewsBundle:NewsCategoryBackend:index }
    
newscategory_new:
    pattern:  /news_category/new
    defaults: { _controller: SystemNewsBundle:NewsCategoryBackend:new }
    
newscategory_show:
    pattern:  /news_category/{id}/show
    defaults: { _controller: SystemNewsBundle:NewsCategoryBackend:show }
    requirements:
      id:  \d+
    
newscategory_create:
    pattern:  /news_category/create
    defaults: { _controller: SystemNewsBundle:NewsCategoryBackend:create }
    
newscategory_edit:
    pattern:  /news_category/{id}/edit
    defaults: { _controller: SystemNewsBundle:NewsCategoryBackend:edit }
    requirements:
          id:  \d+
    
newscategory_update:
    pattern:  /news_category/{id}/update
    defaults: { _controller: SystemNewsBundle:NewsCategoryBackend:update }
    requirements:
          id:  \d+
    
newscategory_delete:
    pattern:  /news_category/{id}/delete
    defaults: { _controller: SystemNewsBundle:NewsCategoryBackend:delete }
    requirements:
          id:  \d+